name: nest-drizzle CI
on:
  pull_request:
    branches:
      - main
      - master
env:
  node: 19.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node }}
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn build

